export const phones = [
  {
    id: 1,
    device: "iPhone 15 Pro Max",
    brand: "Apple",
    price: 1199,
    cpu: 425000,
    gpu: 580000,
    mem: 285000,
    ux: 195000,
    totalscore: 1485000,
    cpuName: "A17 Pro",
    ram: "8GB",
    battery: "4441mAh",
    camera: "48MP Triple Camera",
    insights: [
      "🎮 Perfect for gaming - Runs PUBG/BGMI at Ultra settings with 90+ FPS",
      "⚡ Flagship performance - Future-proof for 4+ years",
    ],
    tags: ["photography", "gaming", "productivity"],
  },
  {
    id: 2,
    device: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    price: 1299,
    cpu: 410000,
    gpu: 560000,
    mem: 290000,
    ux: 185000,
    totalscore: 1445000,
    cpuName: "Snapdragon 8 Gen 3",
    ram: "12GB",
    battery: "5000mAh",
    camera: "200MP Quad Camera",
    insights: [
      "🎮 Perfect for gaming - Runs PUBG/BGMI at Ultra settings with 90+ FPS",
      "📸 Exceptional camera - Professional-grade photography",
    ],
    tags: ["photography", "productivity", "gaming"],
  },
  {
    id: 3,
    device: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    price: 899,
    cpu: 408000,
    gpu: 558000,
    mem: 295000,
    ux: 182000,
    totalscore: 1443000,
    cpuName: "Snapdragon 8 Gen 3",
    ram: "16GB",
    battery: "5300mAh",
    camera: "50MP Quad Camera",
    insights: [
      "🎮 Perfect for gaming - Runs PUBG/BGMI at Ultra settings with 90+ FPS",
      "📸 Great camera - Excellent quality in most conditions",
    ],
    tags: ["photography", "gaming", "value"],
  },
];
